export const mockSneakers = [
  {
    id: 'mock-nike-air-force-1', 
    name: 'Nike Air Force 1',
    brand: 'nike',
    retailPrice: 4900, 
    colorway: 'White',
    releaseDate: '1982-10-26',
    description: 'Легендарные баскетбольные кроссовки 1982 года, ставшие иконой уличной моды. Это первая модель бренда с технологией амортизации Nike Air в подошве.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2693.png?v=1763041096&width=2560',
    sku: 'CW2288-111',
    sizes: [39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-tnf-glenclyffe-black',
    name: 'The North Face Glenclyffe Low Black',
    brand: 'the-north-face',
    retailPrice: 4500,
    compareAtPrice: 6900,
    colorway: 'Black',
    releaseDate: '2025-11-21',
    description: 'Кроссовки The North Face Glenclyffe Low сделаны из переработанного полиэстера и созданы для комфортного передвижения как по городу, так и по пересечённой местности. Мягкая, эластичная конструкция обеспечивает удобную посадку, а вставки из искусственной кожи по бокам добавляют защиты. Лёгкая EVA-подошва отлично гасит удары и снижает нагрузку на суставы. Резиновая подошва Vibram® XS Trek с 4-мм протектором даёт хорошее сцепление и выдерживает активное использование на разных типах поверхности.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_d73a30fd-9cb2-459c-aede-6b36796048ba.png?v=1763638360&width=1200',
    sku: 'TNF-GL-BLK',
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-tnf-glenclyffe-low-beige',
    name: 'The North Face Glenclyffe Low Beige',
    brand: 'the-north-face',
    retailPrice: 4500,
    compareAtPrice: 6900,
    colorway: 'Beige',
    releaseDate: '2025-11-21',
    description: 'Кроссовки The North Face Glenclyffe Low в бежевом цвете сделаны из переработанного полиэстера и созданы для комфортного передвижения как по городу, так и по пересечённой местности. Мягкая, эластичная конструкция обеспечивает удобную посадку, а вставки из искусственной кожи по бокам добавляют защиты. Лёгкая EVA-подошва отлично гасит удары и снижает нагрузку на суставы.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_b6b48e9e-bc59-4e76-8f31-6b0065b48e4a.png?v=1763638360&width=1200',
    sku: 'TNF-GL-BGE',
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-tnf-glenclyffe-high',
    name: 'The North Face Glenclyffe High Black',
    brand: 'the-north-face',
    retailPrice: 7500,
    colorway: 'Black',
    releaseDate: '2025-11-21',
    description: 'Кроссовки The North Face Glenclyffe High — высокая версия культовой модели, созданная для комфортного передвижения как по городу, так и по пересечённой местности. Мягкая, эластичная конструкция обеспечивает удобную посадку, а вставки из искусственной кожи по бокам добавляют защиты. Лёгкая EVA-подошва отлично гасит удары и снижает нагрузку на суставы. Резиновая подошва Vibram® XS Trek с 4-мм протектором даёт хорошее сцепление.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3335.png?v=1763736359&width=1200',
    sku: 'TNF-GL-HIGH-BLK',
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-adidas-gazelle',
    name: 'Adidas Gazelle Pink',
    brand: 'adidas',
    retailPrice: 4900,
    colorway: 'Pink',
    releaseDate: '2024-08-01',
    description: 'Это культовые низкие ретро-кроссовки из мягкой замши розового цвета, ставшие одним из главных стритстайл-трендов последних лет. Модель ценится за винтажную эстетику, легкость и универсальность.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2970.png?v=1763376143&width=1200',
    sku: 'B75807',
    sizes: [36, 37, 38, 39, 40, 41, 42],
  },
  {
    id: 'mock-adidas-gazelle-olympic',
    name: 'Adidas Gazelle Olympic Pack',
    brand: 'adidas',
    retailPrice: 4990,
    colorway: 'Olympic Pack',
    releaseDate: '2025-11-17',
    description: 'adidas Gazelle "Olympic Pack". Классические кроссовки Gazelle в новой расцветке из олимпийской серии. Мягкий замш, удобная посадка, лёгкие и простые в носке. Подходят под любой повседневный стиль — просто хорошие кроссовки на каждый день без лишних заморочек.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3093.png?v=1763452956&width=1200',
    sku: 'B75808',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: 'mock-jordan-air',
    name: 'Air Jordan 4 Midnight Navy',
    brand: 'jordan',
    retailPrice: 6900,
    colorway: 'Midnight Navy',
    releaseDate: '2022-11-29',
    description: 'Air Jordan 4 “Midnight Navy” — стильные кроссовки в сочетании глубокого тёмно-синего и белого цветов. Плотная кожа, фирменные вставки и удобная подошва с Air делают их комфортными на каждый день. Универсальная модель, которая отлично подходит под любой образ.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_0ceff9ef-49ef-450f-894d-4483c68d5e03.png?v=1763306867&width=1200',
    sku: 'DZ5485-612',
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-new-balance-pigment',
    name: 'New Balance 2002 Pigment',
    brand: 'new balance',
    retailPrice: 5500,
    colorway: 'Pigment',
    releaseDate: '2021-06-04',
    description: ' — Это стильное и сдержанное исполнение популярного бегового ретро-силуэта 2000-х годов. Расцветка построена на сочетании глубокого темно-синего (Pigment) и благородного светло-серого (Light Aluminum) оттенков.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2974.png?v=1763376143&width=2560',
    sku: 'U9060ECA',
    sizes: [39, 40, 41, 42, 43, 44],
  },
  {
    id: 'mock-on-cloud-x4-chambray',
    name: 'On Cloud X4 Chambray',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Chambray',
    releaseDate: '2025-01-16',
    description: 'On Cloud X4 — инновационные кроссовки, созданные для тех, кто ценит комфорт и стиль. Легкая конструкция с облачной подошвой обеспечивает амортизацию при каждом шаге, идеально подходя для бега и повседневной носки. Уникальный дизайн Snake добавляет современный вид вашему гардеробу. Дышащий верх поддерживает ноги в прохладе, а надежная фиксация гарантирует стабильность во время активности. Идеальный выбор для спортсменов и любителей комфортной обуви.',
    image: 'https://sneakertown.kg/cdn/shop/files/424489.png?v=1776418122&width=3840',
    sku: 'VN000D3HY28',
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
  },
  {
    id: 'mock-on-cloud-x4-black',
    name: 'On Cloud X4 Black',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Black',
    releaseDate: '2026-04-17',
    description: 'On Cloud X4 Black — инновационные кроссовки, разработанные для спортсменов, требующих максимальной производительности. Легкая конструкция с технологией CloudTec обеспечивает исключительную амортизацию и отзывчивость при каждом шаге.',
    image: 'https://sneakertown.kg/cdn/shop/files/424479.png?v=1776417954&width=1200',
    sku: 'ON-X4-BLK',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloud-x4-white',
    name: 'On Cloud X4 White',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'White',
    releaseDate: '2026-01-26',
    description: 'On Cloud X4 White — инновационные кроссовки, разработанные для спортсменов, требующих максимальной производительности. Легкая конструкция с технологией CloudTec обеспечивает исключительную амортизацию и отзывчивость при каждом шаге. Белый цвет придает универсальный вид, подходящий как для тренировок, так и для повседневной носки.',
    image: 'https://sneakertown.kg/cdn/shop/files/424435.png?v=1769430289&width=1200',
    sku: 'ON-X4-W',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloudmonster-hyper-black',
    name: 'On Cloudmonster Hyper Black',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Black',
    releaseDate: '2025-11-17',
    description: 'Это премиальные беговые кроссовки швейцарского бренда On с экстремальным уровнем амортизации, созданные для профессиональных атлетов и любителей для эффективных тренировок на длинные дистанции.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_99f74ce0-e9a2-440e-884f-02c9d13d009b.png?v=1763385180&width=1200',
    sku: 'ON-CM-HYPER-BLK',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloudmonster-hyper-gradient',
    name: 'On Cloudmonster Hyper Gradient',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Gradient',
    releaseDate: '2025-11-17',
    description: 'Разработанная спортсменами. Для спортсменов. Самая легкая обувь в семействе Cloudmonster с двойной подошвой из пенопласта сочетает в себе максимальную амортизацию и максимальный отскок.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_9956add0-1164-4381-b160-efdc53fb1634.png?v=1763385180&width=1200',
    sku: 'ON-CM-HYPER-GRD',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloudmonster-hyper-grey',
    name: 'On Cloudmonster Hyper Grey',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Grey',
    releaseDate: '2025-11-17',
    description: 'Разработанная спортсменами. Для спортсменов. Самая легкая обувь в семействе Cloudmonster с двойной подошвой из пенопласта сочетает в себе максимальную амортизацию и максимальный отскок.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_a801dc6a-5cce-494b-8757-c083f7feba43.png?v=1763385180&width=1200',
    sku: 'ON-CM-HYPER-GRY',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloudmonster-hyper-red',
    name: 'On Cloudmonster Hyper Red',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Hyper Red',
    releaseDate: '2025-11-17',
    description: 'Разработанная спортсменами. Для спортсменов. Самая легкая обувь в семействе Cloudmonster с двойной подошвой из пенопласта сочетает в себе максимальную амортизацию и максимальный отскок.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_ba3a9094-47c9-4565-a3ac-b523b082a053.png?v=1763385180&width=1200',
    sku: 'ON-CM-HYPER-RED',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloudmonster-espresso',
    name: 'On Cloudmonster Espresso',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Espresso',
    releaseDate: '2025-11-17',
    description: 'On Cloudmonster — культовые кроссовки швейцарского бренда On с максимальной амортизацией. Уникальная технология CloudTec обеспечивает мягкое приземление и мощный отскок. Расцветка Espresso придает модели благородный и универсальный вид.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2691.png?v=1763041096&width=1200',
    sku: 'ON-CM-ESPRESSO',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-salomon-xt6-goretex',
    name: 'Salomon XT-6 Goretex',
    brand: 'salomon',
    retailPrice: 6900,
    colorway: 'Black',
    releaseDate: '2025-11-18',
    description: 'Salomon XT-6 Goretex — легендарные трейловые кроссовки с мембраной GORE-TEX, которые отлично водоотталкивают. Сочетают агрессивный дизайн, максимальную защиту от непогоды и комфорт при активном использовании в любых условиях.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_06dbd220-df39-4881-bd57-f539c5303a53.png?v=1763452286&width=1200',
    sku: 'SAL-XT6-GTX',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-salomon-xt6',
    name: 'Salomon XT-6',
    brand: 'salomon',
    retailPrice: 6900,
    colorway: 'Black',
    releaseDate: '2025-11-13',
    description: 'Salomon XT-6 — культовые трейловые кроссовки с узнаваемым агрессивным дизайном. Обеспечивают надежное сцепление на любых поверхностях, отличную амортизацию и защиту стопы. Идеальный выбор для города и бездорожья.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2692.png?v=1763041096&width=1200',
    sku: 'SAL-XT6',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-nike-x-patta',
    name: 'Nike x Patta "Rush Maroon"',
    brand: 'nike',
    retailPrice: 5000,
    colorway: "Metallic Silver / Rush Maroon",
    releaseDate: '2021-11-19',
    description: 'Nike Air Max 1 x Patta “Rush Maroon” — лимитированная коллаборация с фирменным волнообразным дизайном мудагарда. Премиальная кожа, дышащий mesh и насыщенный бордовый оттенок создают стильный и узнаваемый образ. Классическая амортизация Air обеспечивает комфорт на каждый день. Отличный выбор для ценителей редких выпусков.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_dd206a16-220b-459d-b55e-d6bc3caa2790.png?v=1763306867&width=1200',
    sku: '374915-04',
    sizes: [],
  },
  {
    id: 'mock-golden-goose-ballstar',
    name: 'Golden Goose Ballstar Men',
    brand: 'golden goose',
    retailPrice: 8900,
    colorway: 'White / Black',
    releaseDate: '2023-11-15',
    description: 'Это премиальные итальянские кеды ручной работы, дизайн которых вдохновлен атмосферой американского университетского баскетбола и скейт-культуры 1980-х годов. Главная фишка бренда — эффект искусственного состаривания (distressed look), благодаря которому каждая пара уникальна и выглядит как любимая обувь с историей прямо из коробки.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_13a7abbe-439c-4907-b967-3e9e85025fca.png?v=1763112508&width=1200',
    sku: 'AR0456',
    sizes: [40, 41, 42, 43, 44],
  },
  {
    id: 'mock-adidas-sl72',
    name: 'Adidas SL72 Brown',
    brand: 'adidas',
    retailPrice: 4990,
    colorway: 'Brown',
    releaseDate: '2025-09-27',
    description: 'Это триумфальное возвращение архивных беговых кроссовок 1972 года, которые стали главным стритстайл-хитом наравне с моделями Samba и Gazelle. Аббревиатура SL расшифровывается как Super Lightweight (суперлегкие), поскольку в свое время это была первая модель бренда с революционным нейлоновым верхом.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3092.png?v=1763452364&width=1200',
    sku: '162053C',
    sizes: [37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: 'mock-golden-goose-white',
    name: 'Golden Goose Ballstar2',
    brand: 'golden goose',
    retailPrice: 8900,
    colorway: 'White',
    releaseDate: '2025-07-15',
    description: 'Это обновленное и усовершенствованное переиздание культовых премиальных кед итальянского бренда. Сохранив свою аутентичную эстетику американского баскетбола и скейтбординга 1980-х годов, версия Ball Star 2 предлагает более изящный, современный взгляд на классику и улучшенный комфорт.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_e86e9db3-5785-4331-999a-64c9c6202570.png?v=1763112508&width=1200',
    sku: 'AS0456',
    sizes: [39, 40, 41, 42, 43, 44],
  },
  {
    id: 'mock-new-balance-992',
    name: 'New Balance 992 x JJJound',
    brand: 'new balance',
    retailPrice: 7500,
    colorway: 'Green',
    releaseDate: '2020-07-24',
    description: 'Кроссовки New Balance, произведённые в США, минимум на 70% сделаны из местных материалов. Такие модели выпускаются ограниченным тиражом и занимают небольшую часть ассортимента бренда. New Balance уже более 75 лет делает обувь в США и не снижает планку качества.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-5260.webp?v=1767872796&width=1200',
    sku: 'U7060ECA',
    sizes: [],
  },
  {
    id: 'mock-jordan-air-travis-scott',
    name: 'Travis Scott x Air Jordan 1',
    brand: 'jordan',
    retailPrice: 12000,
    colorway: 'Brown-Black',
    releaseDate: '2019-05-11',
    description: 'Это одна из самых влиятельных, успешных и разыскиваемых коллабораций в истории современной сникер-культуры, полностью перевернувшая рынок лимитированной обуви. Главной визитной карточкой совместных релизов рэпера Трэвиса Скотта (Cactus Jack) и бренда Jordan стал перевернутый логотип Swoosh (Reverse Swoosh) на внешней стороне кроссовка.',
    image: 'https://sneakertown.kg/cdn/shop/files/Instagram_post_-_56_8b203a22-96b3-48d0-a1f0-72bfae505896.png?v=1762949858&width=1200',
    sku: 'DZ5483-612',
    sizes: [],
  },
  {
    id: 'mock-on-cloud-2-white',
    name: 'On Cloud Cloudmonster 2',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'White',
    releaseDate: '2024-02-22',
    description: 'Высокопроизводительные кроссовки, разработанные для максимального комфорта и поддержки. Инновационная облачная подошва обеспечивает исключительную амортизацию с каждым шагом, идеально подходя для бега, тренировок и повседневной носки. Легкая конструкция снижает нагрузку на ноги, а дышащий верх поддерживает оптимальную температуру. Надежная фиксация гарантирует стабильность во время интенсивной активности. Классический черный цвет универсален и легко сочетается с любым стилем. Идеальный выбор для спортсменов и тех, кто ценит качество и функциональность в каждой паре обуви.',
    image: 'https://sneakertown.kg/cdn/shop/files/424482.png?v=1776418289&width=1200',
    sku: 'VN030D3HY28',
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
  },
  {
    id: 'mock-on-cloud-cloudmonster-2-black',
    name: 'On Cloud Cloudmonster 2 Black',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Black',
    releaseDate: '2026-04-17',
    description: 'On Cloudmonster 2 Black — высокопроизводительные кроссовки, разработанные для максимального комфорта и поддержки. Инновационная облачная подошва обеспечивает исключительную амортизацию с каждым шагом, идеально подходя для бега, тренировок и повседневной носки.',
    image: 'https://sneakertown.kg/cdn/shop/files/424486.png?v=1776418194&width=1200',
    sku: 'ON-CM2-BLK',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-peak-paf-black',
    name: 'On Peak Paf Black',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Black',
    releaseDate: '2025-11-18',
    description: 'On Peak PAF Black — коллаборация On с POST ARCHIVE FACTION. Обувь отличается низким силуэтом и эстетикой, вдохновленной стеблем лотоса. Переосмысленный дизайн и передовые технологии On для максимального комфорта.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_42ee297e-c5e9-4e48-b923-bfeac114a08f.png?v=1763447233&width=1200',
    sku: 'ON-PEAK-PAF-BLK',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-loewe-cloudtilt-all-black',
    name: 'On x Loewe Cloudtilt 2.0 All Black',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Black',
    releaseDate: '2025-11-23',
    description: 'On x Loewe Cloudtilt 2.0 "All Black" — коллаборация швейцарского бренда On с испанским модным домом Loewe. Модель сочетает передовые амортизирующие технологии On и минималистичный дизайн от Loewe. Полностью черный цвет делает кроссовки универсальными и стильными.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3444.png?v=1763892125&width=1200',
    sku: 'ON-LOEWE-CT-BLK',
    sizes: [38, 39, 40, 41, 42, 44],
  },
  {
    id: 'mock-on-loewe-cloudtilt-white',
    name: 'On x Loewe Cloudtilt White',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'White',
    releaseDate: '2026-01-26',
    description: 'On x Loewe Cloudtilt — результат сотрудничества швейцарского бренда спортивной обуви с испанским домом моды. Кроссовки в светлом исполнении сочетают инновационную технологию CloudTec для амортизации с минималистичным дизайном Loewe. Верх выполнен из премиальных материалов с характерными деталями люксового бренда.',
    image: 'https://sneakertown.kg/cdn/shop/files/424435_fbdee66c-a4b8-446e-b7dd-c54f5cfc596a.png?v=1769431088&width=1200',
    sku: 'ON-LOEWE-CT-W',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloudzone-moon',
    name: 'ON Cloudzone Moon',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Moon',
    releaseDate: '2025-11-12',
    description: 'ON Cloudzone Moon обеспечивает отзывчивую амортизацию, разработанную для длительного бега. Технология CloudTec поглощает удары при каждом шаге, одновременно возвращая энергию, позволяя вам поддерживать темп на протяжении всей дистанции. Легкая конструкция снижает усталость, а надежная посадка фиксирует стопу во время интенсивных тренировок.',
    image: 'https://sneakertown.kg/cdn/shop/files/Instagram_post_-_56.png?v=1762949754&width=1200',
    sku: 'ON-CLOUDZONE-MOON',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloudsurfer-2-trail-desert',
    name: 'ON Cloudsurfer 2 Trail Desert',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Desert',
    releaseDate: '2025-11-12',
    description: 'ON Cloudsurfer 2 Trail Desert — трейловые кроссовки для бега по пересеченной местности. Сочетают мягкую амортизацию CloudTec и надежное сцепление на бездорожье. Легкая конструкция и дышащий верх обеспечивают комфорт на длительных дистанциях.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2653.png?v=1762955076&width=1200',
    sku: 'ON-CS2-TRAIL-DESERT',
    sizes: [37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloudsurfer-2-trail-black-white',
    name: 'ON Cloudsurfer 2 Trail Black White',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Black White',
    releaseDate: '2025-11-17',
    description: 'ON Cloudsurfer 2 Trail — трейловые кроссовки для бега по пересеченной местности. Сочетают мягкую амортизацию CloudTec и надежное сцепление на бездорожье. Легкая конструкция и дышащий верх обеспечивают комфорт на длительных дистанциях.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2655.png?v=1762955076&width=1200',
    sku: 'ON-CS2-TRAIL-BW',
    sizes: [38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloudsurfer-2-trail-khaki',
    name: 'ON Cloudsurfer 2 Trail Khaki',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Khaki',
    releaseDate: '2025-11-17',
    description: 'ON Cloudsurfer 2 Trail — трейловые кроссовки для бега по пересеченной местности. Сочетают мягкую амортизацию CloudTec и надежное сцепление на бездорожье. Легкая конструкция и дышащий верх обеспечивают комфорт на длительных дистанциях.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2648.png?v=1762954374&width=1200',
    sku: 'ON-CS2-TRAIL-KHAKI',
    sizes: [37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloudsurfer-2-blue',
    name: 'On Cloudsurfer 2 Blue',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Blue',
    releaseDate: '2025-11-17',
    description: 'On Cloudsurfer 2 — это обновленная версия беговых кроссовок от швейцарского бренда On, предназначенная для ежедневных тренировок по асфальту. Они сочетают в себе комфорт, стабильность и инновации, такие как усовершенствованная технология подошвы CloudTec Phase™ для более плавного и мягкого бега.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2856.png?v=1763281604&width=1200',
    sku: 'ON-CS2-BLUE',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-loewe-cloudsolo',
    name: 'On Loewe Cloudsolo White',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'White',
    releaseDate: '2025-11-16',
    description: 'On Loewe Cloudsolo — первая совместная коллекция кроссовок испанского модного дома Loewe и швейцарского бренда On. Лимитированная модель Cloudsolo сочетает передовые технологии On с минималистичной эстетикой Loewe.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_52df72aa-9669-467e-96cd-26f32ee0bcb6.png?v=1763279845&width=1200',
    sku: 'ON-LOEWE-CLOUDSOLO-W',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-loewe-white',
    name: 'On Loewe White',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'White',
    releaseDate: '2025-11-17',
    description: 'On Loewe — коллекция кроссовок и одежды от испанского модного дома Loewe и швейцарского бренда спортивной обуви On. Она включает в себя лимитированную модель кроссовок, сочетающую технологии On с эстетикой Loewe, а также одежду в спортивном стиле.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_86655a4e-bc23-47d1-8311-0d029279ab84.png?v=1763279847&width=1200',
    sku: 'ON-LOEWE-W',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-on-cloud-x4-snake',
    name: 'On Cloud X4 Snake',
    brand: 'on cloud',
    retailPrice: 7900,
    colorway: 'Snake',
    releaseDate: '2024-12-18',
    description: 'Инновационные кроссовки, созданные для тех, кто ценит комфорт и стиль. Легкая конструкция с облачной подошвой обеспечивает амортизацию при каждом шаге, идеально подходя для бега и повседневной носки. Уникальный дизайн Snake добавляет современный вид вашему гардеробу. Дышащий верх поддерживает ноги в прохладе, а надежная фиксация гарантирует стабильность во время активности. Идеальный выбор для спортсменов и любителей комфортной обуви.',
    image: 'https://sneakertown.kg/cdn/shop/files/424492.png?v=1776418037&width=1200',
    sku: 'VN000D3HY88',
    sizes: [40, 42],
  },
  {
    id: 'mock-new-balance-2002',
    name: 'New Balance 2002 Castlerock',
    brand: 'new balance',
    retailPrice: 5500,
    colorway: 'Grey',
    releaseDate: '2022-08-16',
    description: 'Это премиальное серое исполнение культового бегового ретро-силуэта, которое считается идеальным воплощением фирменной эстетики бренда. Цвет Castlerock представляет собой глубокий, благородный оттенок темно-серого камня, который выглядит дорого благодаря многослойной комбинации материалов.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3475_ac7ad63e-40cb-4497-8a4e-fba0a167dcc8.png?v=1763980795&width=2560',
    sku: 'U7060ECE',
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-onitsuka-tiger-yellow',
    name: 'Onitsuka Tiger 66 Yellow',
    brand: 'onitsuka',
    retailPrice: 4900,
    colorway: 'Yellow',
    releaseDate: '2022-12-01',
    description: 'В жёлтом цвете: лёгкие, гибкие кроссовки в фирменном ретро-стиле бренда. Верх выполнен из мягкой кожи с замшевыми деталями, а тонкая резиновая подошва обеспечивает комфорт на каждый день. Узнаваемые полоски сбоку и яркий жёлтый цвет делают модель заметной и легко сочетаемой с базовой одеждой. Отличный вариант для повседневной носки и лайтовых прогулок.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3398.png?v=1763815110&width=1200',
    sku: 'U70606CE',
    sizes: [37, 38, 39, 40, 41, 42, 43],
  },
  {
    id: 'mock-onitsuka-tiger-green',
    name: 'Onitsuka Tiger 66 Green',
    brand: 'onitsuka',
    retailPrice: 4900,
    colorway: 'Green',
    releaseDate: '2022-10-16',
    description: 'В зеленом цвете: лёгкие, гибкие кроссовки в фирменном ретро-стиле бренда. Верх выполнен из мягкой кожи с замшевыми деталями, а тонкая резиновая подошва обеспечивает комфорт на каждый день.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3401.png?v=1763815434&width=3840',
    sku: '970606CE',
    sizes: [37, 38, 39, 40, 41, 42, 43],
  },
  {
    id: 'mock-onitsuka-tiger-grey',
    name: 'Onitsuka Tiger 66 Grey',
    brand: 'onitsuka',
    retailPrice: 4900,
    colorway: 'Grey',
    releaseDate: '2022-11-10',
    description: 'В сером цвете: лёгкие, гибкие кроссовки в фирменном ретро-стиле бренда. Верх выполнен из мягкой кожи с замшевыми деталями, а тонкая резиновая подошва обеспечивает комфорт на каждый день.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3397.png?v=1763815995&width=1200',
    sku: '972606CE',
    sizes: [37, 38, 39, 40, 41, 42, 43],
  },
  {
    id: 'mock-onitsuka-tiger-black-white',
    name: 'Onitsuka Tiger 66 Black-White',
    brand: 'onitsuka',
    retailPrice: 4900,
    colorway: 'Black-White',
    releaseDate: '2023-01-20',
    description: 'В черно-белом цвете: лёгкие, гибкие кроссовки в фирменном ретро-стиле бренда. Верх выполнен из мягкой кожи с замшевыми деталями, а тонкая резиновая подошва обеспечивает комфорт на каждый день.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3396.png?v=1763815653&width=1200',
    sku: '972609CE',
    sizes: [36, 37, 38, 39, 40, 41, 42],
  },
  {
    id: 'mock-onitsuka-tiger-classic',
    name: 'Onitsuka Tiger 66',
    brand: 'onitsuka',
    retailPrice: 5500,
    colorway: 'White',
    releaseDate: '2022-09-20',
    description: 'В универсальном цвете: лёгкие, гибкие кроссовки в фирменном ретро-стиле бренда. Верх выполнен из мягкой кожи с замшевыми деталями, а тонкая резиновая подошва обеспечивает комфорт на каждый день.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3399.png?v=1763815903&width=1200',
    sku: '972686CE',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: 'mock-onitsuka-tiger-gold',
    name: 'Onitsuka Tiger 66 White Gold',
    brand: 'onitsuka',
    retailPrice: 4900,
    colorway: 'White-Gold',
    releaseDate: '2022-11-29',
    description: 'В бело-золотом цвете: лёгкие, гибкие кроссовки в фирменном ретро-стиле бренда. Верх выполнен из мягкой кожи с замшевыми деталями, а тонкая резиновая подошва обеспечивает комфорт на каждый день.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-3400.png?v=1763815867&width=1200',
    sku: '972686DE',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43],
  },
  {
    id: 'mock-onitsuka-corsair',
    name: 'Onitsuka Corsair',
    brand: 'onitsuka',
    retailPrice: 5900,
    colorway: 'Blue',
    releaseDate: '2024-09-29',
    description: 'Классический кроссовок с богатой историей и современным стилем. Модель отличается удобной посадкой, качественными материалами и узнаваемым дизайном японского бренда. Синий цвет придает универсальность, позволяя легко комбинировать с различными нарядами. Идеален для повседневной носки, спорта и уличного стиля. Corsair сочетает ретро-эстетику с функциональностью, обеспечивая комфорт на весь день. Отличный выбор для любителей качественной спортивной обуви.',
    image: 'https://sneakertown.kg/cdn/shop/files/1183C317_401_SR_RT_GLB.webp?v=1776423730&width=1200',
    sku: '972M86DE',
    sizes: [39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-onitsuka-corsair-pink',
    name: 'Onitsuka Tiger Corsair Pink',
    brand: 'onitsuka',
    retailPrice: 5900,
    colorway: 'Pink',
    releaseDate: '2026-04-17',
    description: 'Onitsuka Tiger Corsair Pink — классический кроссовок с богатой историей и современным стилем. Модель отличается удобной посадкой, качественными материалами и узнаваемым дизайном японского бренда. Розовый цвет придает универсальность, позволяя легко комбинировать с различными нарядами. Идеален для повседневной носки, спорта и уличного стиля.',
    image: 'https://sneakertown.kg/cdn/shop/files/1183C317_700_SR_RT_GLB.webp?v=1776423862&width=1200',
    sku: '1183C317-700',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-timberland-boots-black',
    name: 'Timberland Boots Waterproof Black',
    brand: 'timberland',
    retailPrice: 5000,
    colorway: 'Black',
    releaseDate: '2025-10-08',
    description: 'Это культовые всесезонные ботинки, которые объединяют брутальный утилитарный стиль и абсолютную защиту от непогоды. В полностью черном цвете (Triple Black) они стали классикой городского стиля и практичной альтернативой традиционным желтым ботинкам бренда.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_3cd98903-9c00-43f3-b189-bcba69e4cfe7.png?v=1763198817&width=1200',
    sku: '978K86KU',
    sizes: [40, 41, 42, 43, 44, 45, 46],
  },
   {
    id: 'mock-timberland-boots-orange',
    name: 'Timberland Boots Waterproof Orange',
    brand: 'timberland',
    retailPrice: 5000,
    colorway: 'Orange',
    releaseDate: '2025-10-08',
    description: 'Это легендарная всепогодная обувь, ставшая глобальным культурным феноменом и эталоном надежности. Созданные в 1973 году как износостойкие рабочие ботинки, они приобрели культовый статус в индустрии моды и хип-хоп культуре благодаря своей долговечности и узнаваемому силуэту.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_d34246ef-2c02-4d84-a3ab-4392a9411458.png?v=1763198799&width=3840',
    sku: '978K80KU',
    sizes: [40, 41, 42, 43, 44, 45, 46],
  },
  {
    id: 'mock-timberland-premium',
    name: 'Timberland 6 inch Premium Waterproof',
    brand: 'timberland',
    retailPrice: 6000,
    colorway: 'Orange',
    releaseDate: '2025-09-27',
    description: 'Легендарные ботинки Timberland 6 inch Premium Waterproof — воплощение надежности и стиля. Водонепроницаемая конструкция защищает ноги в любых погодных условиях, а премиум-материалы обеспечивают долговечность и комфорт при длительной носке. Классический дизайн с прочной подошвой идеален для города и природы. Проверенная временем модель, которая не теряет актуальность благодаря универсальности и качеству исполнения. Инвестиция в обувь, которая прослужит годы.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_f9e28fdc-cdd8-4438-a1e7-1967cca08122.png?v=1763198365&width=1200',
    sku: '978K78KU',
    sizes: [41, 42, 43, 44, 45, 46],
  },
  {
    id: 'mock-zegna-triple-stitch',
    name: 'Zegna Dark Brown Leather Triple Stitch',
    brand: 'zegna',
    retailPrice: 13000,
    compareAtPrice: 18000,
    colorway: 'Dark Brown',
    releaseDate: '2025-11-12',
    description: 'Zegna Dark Brown Leather Triple Stitch с мехом — премиальный выбор для ценителей качественной обуви. Изготовлены из мягкой кожи темно-коричневого оттенка с характерной тройной строчкой. Внутренняя отделка из меха обеспечивает исключительное тепло и комфорт в холодное время года.',
    image: 'https://sneakertown.kg/cdn/shop/files/FEEE715C-07B8-42AA-9C82-3F6D646DF750.jpg?v=1765285510&width=1200',
    sku: 'ZEGNA-DB-TS',
    sizes: [41, 42, 43, 44],
  },
  {
    id: 'mock-zegna-triple-stitch-secondskin',
    name: 'Zegna Triple Stitch Secondskin',
    brand: 'zegna',
    retailPrice: 12500,
    colorway: 'Blue',
    releaseDate: '2026-05-14',
    description: 'Zegna Triple Stitch Secondskin в глубоком синем цвете — воплощение итальянского мастерства и современного минимализма. Культовая модель с характерной тройной строчкой на боку, которая стала символом бренда, теперь в благородном синем оттенке. Премиальный материал обеспечивает идеальную посадку и комфорт при длительном ношении.',
    image: 'https://sneakertown.kg/cdn/shop/files/424534.png?v=1778751965&width=1200',
    sku: 'ZEGNA-TS-SS',
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-zegna-triple-stitch-monte',
    name: 'Zegna Triple Stitch Leather Monte',
    brand: 'zegna',
    retailPrice: 18000,
    colorway: 'White',
    releaseDate: '2025-11-12',
    description: 'Элегантные кроссовки Zegna Triple Stitch Leather Monte из премиальной белой кожи с характерной тройной строчкой — культовым символом итальянского бренда. Модель воплощает философию современного минимализма и подходит как для деловых образов, так и для повседневной носки. Качественные материалы и безупречная обработка швов обеспечивают долговечность и комфорт.',
    image: 'https://sneakertown.kg/cdn/shop/files/triple-stitch-leather-monte-sneakers-men.jpg?v=1762925651&width=1200',
    sku: 'ZEGNA-TS-LM',
    sizes: [45],
  },
  {
    id: 'mock-adidas-spezial-handball',
    name: 'Adidas Spezial Handball',
    brand: 'adidas',
    retailPrice: 4990,
    colorway: 'Blue',
    releaseDate: '2025-06-01',
    description: 'adidas Handball Spezial в синем цвете — классические кроссовки с замшевым верхом и фирменными белыми тремя полосками. Лёгкие, удобные и хорошо сидят на ноге. Глубокий синий цвет делает модель универсальной — подходит и для повседневного стиля, и для спортивного образа. Отличный вариант для тех, кто любит ретро-классику adidas.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_8bbbf855-9231-44cd-95dc-dbfd2a420074.png?v=1763306867&width=1200',
    sku: 'ADI-SPEZIAL-HB-BLU',
    sizes: [38, 39, 40, 41],
  },
  {
    id: 'mock-adidas-gazelle-green',
    name: 'Adidas Gazelle Green',
    brand: 'adidas',
    retailPrice: 4900,
    colorway: 'Green',
    releaseDate: '2025-06-01',
    description: 'Культовые низкие ретро-кроссовки из мягкой замши зелёного цвета, ставшие одним из главных стритстайл-трендов последних лет. Модель ценится за винтажную эстетику, легкость и универсальность. Глубокий зелёный оттенок вписывается в любой повседневный образ.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2690.png?v=1763041096&width=1200',
    sku: 'B75809',
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-new-balance-992-core-usa',
    name: 'New Balance 992 Core, USA',
    brand: 'new balance',
    retailPrice: 6500,
    colorway: 'Grey',
    releaseDate: '2025-06-01',
    description: 'Кроссовки New Balance, произведённые в США, минимум на 70% сделаны из местных материалов. Такие модели выпускаются ограниченным тиражом и занимают небольшую часть ассортимента бренда. New Balance уже более 75 лет делает обувь в США и не снижает планку качества.',
    image: 'https://sneakertown.kg/cdn/shop/files/424435_43a82ef8-5eca-463b-8e14-90907a13a2f7.png?v=1769430886&width=1200',
    sku: 'M992GR',
    sizes: [37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-new-balance-2002-grey',
    name: 'New Balance 2002 Grey',
    brand: 'new balance',
    retailPrice: 5500,
    colorway: 'Grey',
    releaseDate: '2025-06-01',
    description: 'Классический беговой ретро-силуэт 2000-х годов от New Balance. Сочетает комфорт, качественные материалы и узнаваемый дизайн. Подходит для повседневной носки и активного отдыха.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2973.png?v=1763376143&width=1200',
    sku: 'M2002RGR',
    sizes: [37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-ugg-lowmel-brown',
    name: 'UGG Lowmel Brown',
    brand: 'ugg',
    retailPrice: 5500,
    compareAtPrice: 7100,
    colorway: 'Brown',
    releaseDate: '2025-06-01',
    description: 'UGG Lowmel — это низкие зимние ботинки с мягкой теплой подкладкой. Они удобные, легкие и отлично сохраняют тепло зимой. Идеально подходят для повседневной носки в холодную погоду и легко сочетаются с любой одеждой.',
    image: 'https://sneakertown.kg/cdn/shop/files/424440.png?v=1769599350&width=1200',
    sku: 'UGG-LOWMEL-BRN',
    sizes: [36, 37, 38, 39, 40, 41],
  },
  {
    id: 'mock-ugg-lowmel-sand',
    name: 'UGG Lowmel Sand',
    brand: 'ugg',
    retailPrice: 5500,
    compareAtPrice: 7100,
    colorway: 'Sand',
    releaseDate: '2025-06-01',
    description: 'UGG Lowmel — это низкие зимние ботинки с мягкой теплой подкладкой. Они удобные, легкие и отлично сохраняют тепло зимой. Идеально подходят для повседневной носки в холодную погоду и легко сочетаются с любой одеждой.',
    image: 'https://sneakertown.kg/cdn/shop/files/1_1d7f8dcf-abf9-4567-8125-abaddaf706f7.png?v=1769599217&width=1200',
    sku: 'UGG-LOWMEL-SAND',
    sizes: [36, 37, 38, 39, 40, 41],
  },
  {
    id: 'mock-louis-vuitton-tatic-runner',
    name: 'Louis Vuitton Tatic Runner',
    brand: 'louis vuitton',
    retailPrice: 12500,
    colorway: 'Blue',
    releaseDate: '2025-06-01',
    description: 'Louis Vuitton Tatic Runner — современный кроссовок, сочетающий спортивный стиль с люксовым дизайном. Синий цвет придает обуви свежесть и универсальность, идеально подходя как для повседневных прогулок, так и для активного отдыха. Модель отличается комфортной посадкой и качественными материалами, характерными для бренда Louis Vuitton.',
    image: 'https://sneakertown.kg/cdn/shop/files/424539.png?v=1778752299&width=1200',
    sku: 'LV-TATIC-RUNNER-BLU',
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 'mock-ugg-lowmel-black',
    name: 'UGG Lowmel Black',
    brand: 'ugg',
    retailPrice: 5000,
    compareAtPrice: 7100,
    colorway: 'Black',
    releaseDate: '2025-06-01',
    description: 'UGG Lowmel — это низкие зимние ботинки с мягкой теплой подкладкой. Они удобные, легкие и отлично сохраняют тепло зимой. Идеально подходят для повседневной носки в холодную погоду и легко сочетаются с любой одеждой.',
    image: 'https://sneakertown.kg/cdn/shop/files/1.png?v=1769598329&width=1200',
    sku: 'UGG-LOWMEL-BLK',
    sizes: [36, 37, 38, 39, 40, 41],
  },
  {
    id: 'mock-ugg-tasman-slipper-high',
    name: 'UGG Tasman Slipper High',
    brand: 'ugg',
    retailPrice: 3600,
    compareAtPrice: 6500,
    colorway: 'Chestnut',
    releaseDate: '2025-06-01',
    description: 'UGG Tasman Slipper High — высокие домашние тапочки из мягкого замша с теплой подкладкой. Удобные, легкие и стильные, идеально подходят для повседневной носки в холодное время года.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene.png?v=1763112507&width=1200',
    sku: 'UGG-TASMAN-HI-CH',
    sizes: [36, 37, 38, 39, 40, 41],
  },
  {
    id: 'mock-ugg-tasman-slipper',
    name: 'UGG Tasman Slipper',
    brand: 'ugg',
    retailPrice: 3600,
    compareAtPrice: 6500,
    colorway: 'Chestnut',
    releaseDate: '2025-06-01',
    description: 'UGG Tasman Slipper — классические домашние тапочки из мягкого замша с теплой подкладкой. Удобные, легкие и стильные, идеально подходят для повседневной носки дома и на улице.',
    image: 'https://sneakertown.kg/cdn/shop/files/scene_36d0bac9-b7df-4d0b-85cb-527af8ce2a2f.png?v=1763112509&width=1200',
    sku: 'UGG-TASMAN-SL-CH',
    sizes: [36, 37, 38, 39, 40, 41],
  },
  {
    id: 'mock-ugg-lowmel-sand-full',
    name: 'UGG Lowmel Sand',
    brand: 'ugg',
    retailPrice: 7100,
    colorway: 'Sand',
    releaseDate: '2025-06-01',
    description: 'UGG Lowmel — это низкие зимние ботинки с мягкой теплой подкладкой. Они удобные, легкие и отлично сохраняют тепло зимой. Идеально подходят для повседневной носки в холодную погоду и легко сочетаются с любой одеждой.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2728.png?v=1763108518&width=1200',
    sku: 'UGG-LOWMEL-SAND-FULL',
    sizes: [36, 37, 38, 39, 40, 41],
  },
  {
    id: 'mock-ugg-slipper',
    name: 'UGG Slipper',
    brand: 'ugg',
    retailPrice: 3900,
    compareAtPrice: 6500,
    colorway: 'Chestnut',
    releaseDate: '2025-06-01',
    description: 'UGG Slipper — классические домашние тапочки из мягкого замша с теплой подкладкой. Мягкие, лёгкие и невероятно удобные, они сохраняют тепло и дарят комфорт в холодное время года. Идеальны для дома и повседневной носки.',
    image: 'https://sneakertown.kg/cdn/shop/files/IMG-2696.png?v=1763042525&width=1200',
    sku: 'UGG-SLIPPER-CH',
    sizes: [36, 37, 38, 39, 40, 41],
  },
];
